# Generated by Django 4.0.6 on 2022-07-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.IntegerField(verbose_name='러닝타임'),
        ),
    ]
