# Generated by Django 4.0.6 on 2022-07-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.TextField(blank=True, verbose_name='이미지 링크'),
        ),
    ]
