# Generated by Django 4.0.6 on 2022-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.TextField(verbose_name='이미지 링크'),
        ),
    ]
