# Generated by Django 4.0.6 on 2022-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster',
            field=models.TextField(default='', verbose_name='포스터 링크'),
        ),
    ]
