# Generated by Django 4.0.6 on 2022-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.CharField(choices=[('title', '제목 오름차순'), ('-title', '제목 내림차순'), ('star', '별점 오름차순'), ('-star', '별점 내림차순'), ('order', '러닝타임 오름차순'), ('-order', '러닝타임 내림차순')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
