# Generated by Django 4.0.6 on 2022-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.CharField(choices=[('title', '제목 오름차순'), ('star', '별점 오름차순'), ('order', '러닝타임 오름차순')], max_length=10),
        ),
    ]
